export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_CART_DETAILS = "GET_CART_DETAILS";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_BY_SALES = "GET_PRODUCTS_BY_SALES";
export const GET_PRODUCTS_BY_ARRIVAL = "GET_PRODUCTS_BY_ARRIVAL";
export const GET_ARTISTS = "GET_ARTISTS";
export const ADD_ARTIST = "ADD_ARTIST";
export const REMOVE_ARTIST = "REMOVE_ARTIST";
export const GET_GENRES = "GET_GENRES";
export const ADD_GENRE = "ADD_GENRE";
export const REMOVE_GENRE = "REMOVE_GENRE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const CLEAR_PRODUCT_DETAILS = "CLEAR_PRODUCT_DETAILS";

export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const CLEAR_CURRENT_TRACK = "CLEAR_CURRENT_TRACK";
export const SET_PLAY_STATUS = "SET_PLAY_STATUS";
