export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_BY_SALES = "GET_PRODUCTS_BY_SALES";
export const GET_PRODUCTS_BY_ARRIVAL = "GET_PRODUCTS_BY_ARRIVAL";
export const GET_ARTISTS = "GET_ARTISTS";
export const ADD_ARTIST = "ADD_ARTIST";
export const GET_GENRES = "GET_GENRES";
export const ADD_GENRE = "ADD_GENRE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
